name: GitHub CI

on:
  push:
    tags:
      - '**'
    branches:
      - main
  pull_request:

env:
  LLVM_VERSION: 19.1.0

jobs:
    linux:
        name: Linux Build
        runs-on: ubuntu-24.04
        permissions: write-all
        strategy:
            fail-fast: false
            matrix:
                CMAKE_BUILD_TYPE:
                -   Debug
                -   MinSizeRel
                -   RelWithDebInfo
                -   Release
        steps:
        - name: Free Disk Space (Ubuntu)
          uses: insightsengineering/disk-space-reclaimer@v1
          with:
            # all of these default to true, but feel free to set to
            # "false" if necessary for your workflow
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true
            docker-images: true
            tools-cache: true
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: sudo apt install -y ninja-build clang
        - name: Build LLVM
          id: BUILD
          run: ./build
          env:
            CMAKE_BUILD_TYPE: ${{matrix.CMAKE_BUILD_TYPE}}
            LLVM_RELEASE_BASENAME: llvm-${{env.LLVM_VERSION}}-x86_64-linux-${{matrix.CMAKE_BUILD_TYPE}}
        - name: Release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            files: |
              ${{steps.BUILD.outputs.DEPLOY_FILE}}00
              ${{steps.BUILD.outputs.DEPLOY_FILE}}01
              ${{steps.BUILD.outputs.DEPLOY_FILE}}02
              ${{steps.BUILD.outputs.DEPLOY_FILE}}03
              ${{steps.BUILD.outputs.DEPLOY_FILE}}04
              ${{steps.BUILD.outputs.DEPLOY_FILE}}.b2sum
    macos:
        name: MacOS Build
        runs-on: macos-15
        permissions: write-all
        strategy:
            fail-fast: false
            matrix:
                CMAKE_BUILD_TYPE:
                -   Debug
                -   MinSizeRel
                -   RelWithDebInfo
                -   Release
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: brew install ninja coreutils
        - name: Build LLVM
          id: BUILD
          run: ./build
          env:
            CMAKE_BUILD_TYPE: ${{matrix.CMAKE_BUILD_TYPE}}
            LLVM_RELEASE_BASENAME: llvm-${{env.LLVM_VERSION}}-aarch64-macos-${{matrix.CMAKE_BUILD_TYPE}}
        - name: Release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            files: |
              ${{steps.BUILD.outputs.DEPLOY_FILE}}00
              ${{steps.BUILD.outputs.DEPLOY_FILE}}01
              ${{steps.BUILD.outputs.DEPLOY_FILE}}02
              ${{steps.BUILD.outputs.DEPLOY_FILE}}03
              ${{steps.BUILD.outputs.DEPLOY_FILE}}04
              ${{steps.BUILD.outputs.DEPLOY_FILE}}.b2sum
