name: GitHub CI

on:
  push:
    tags:
      - '**'
    branches:
      - main
  pull_request:

env:
  LLVM_VERSION: 19.1.0
  LINUX_IMAGE: "ubuntu-24.04"
  MACOS_IMAGE: "macos-15"
  WINDOWS_IMAGE: "windows-2022"

jobs:
    build_llvm:
        name: Build LLVM
        runs-on: ${{matrix.os }}
        permissions: write-all
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-24.04, macos-15]
            CMAKE_BUILD_TYPE:
              -   Debug
              -   MinSizeRel
              -   RelWithDebInfo
              -   Release
        steps:
        - name: Maximize build space
          uses: AdityaGarg8/remove-unwanted-software@v4.1
          with:
            remove-android: 'true'
            remove-dotnet: 'true'
            remove-haskell: 'true'
            remove-codeql: 'true'
            remove-docker-images: 'true'
            remove-large-packages: 'true'
            remove-cached-tools: 'true'
            remove-swapfile: 'true'
          if: matrix.os == env.LINUX_IMAGE
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: sudo apt install -y ninja-build clang
          if: matrix.os == env.LINUX_IMAGE
        - name: Install dependencies
          run: brew install ninja coreutils
          if: matrix.os == env.MACOS_IMAGE
        - name: Build LLVM
          id: BUILD
          run: ./build
          env:
            CMAKE_BUILD_TYPE: ${{matrix.CMAKE_BUILD_TYPE}}
            LLVM_RELEASE_BASENAME: llvm-${{env.LLVM_VERSION}}-${{matrix.os}}-${{matrix.CMAKE_BUILD_TYPE}}
        - name: Disk space
          run: df -h
