name: GitHub CI

on:
  push:
    tags:
      - '**'
  pull_request:

jobs:
    linux:
        name: Linux Build
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                CMAKE_BUILD_TYPE:
                -   Debug
                -   MinSizeRel
                -   RelWithDebInfo
                -   Release

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: sudo apt install -y ninja-build
        - name: Build LLVM
          run: ./build
          env:
            CMAKE_BUILD_TYPE: ${{matrix.CMAKE_BUILD_TYPE}}
    macos:
        name: MacOS Build
        runs-on: macos-15
        strategy:
            fail-fast: false
            matrix:
                CMAKE_BUILD_TYPE:
                -   Debug
                -   MinSizeRel
                -   RelWithDebInfo
                -   Release

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: brew install ninja
        - name: Build LLVM
          run: ./build
          env:
            CMAKE_BUILD_TYPE: ${{matrix.CMAKE_BUILD_TYPE}}


